var NAV_PERMISOS={
 'navMesas':null,
 'navInventario':'gestionar_inventario',
 'navAnalisisInventario':'can_access_inventory_analytics',
 'navConfiguracion':'gestionar_configuracion',
 'navConfigInventario':'gestionar_configuracion',
  'navCaja':'ver_caja',
  'navFinanzas':'__SOLO_ADMIN__',
  'navProveedores':'gestionar_proveedores',
 'navCompras':'gestionar_proveedores',
 'navUsuarios':'crear_usuarios',
 'navReportes':'ver_reportes',
 'navFacturacion':'ver_caja',
 'navMermas':'registrar_mermas',
 'navSpeedBar':'gestionar_inventario',
 'navSocios':'ver_caja',
 'navVales':'ver_caja'
};
var MODULO_PERMISOS={
 'iniciarInventario':'gestionar_inventario',
 'iniciarAnalisisInventario':'can_access_inventory_analytics',
 'iniciarConfiguracion':'gestionar_configuracion',
 'iniciarConfiguracionInventario':'gestionar_configuracion',
 'iniciarCaja':'ver_caja',
 'iniciarProveedores':'gestionar_proveedores',
 'iniciarCompras':'gestionar_proveedores',
 'iniciarUsuarios':'crear_usuarios',
 'iniciarReportes':'ver_reportes',
 'iniciarFacturacion':'ver_caja',
 'iniciarMermas':'registrar_mermas',
 'iniciarSpeedBar':'gestionar_inventario',
 'iniciarSocios':'ver_caja',
 'iniciarVales':'ver_caja'
};
function esAdmin(){try{var u=typeof usuario!=='undefined'?usuario:null;if(!u)try{u=JSON.parse(localStorage.getItem('usuario')||'null');}catch(e){}if(!u)return false;if(Number(u.id_rol)===1)return true;var r=(u.rol||'').toLowerCase();return r==='administrador'||r==='admin';}catch(e){return false;}}
function esRolOperativo(){try{var u=typeof usuario!=='undefined'?usuario:null;if(!u)try{u=JSON.parse(localStorage.getItem('usuario')||'null');}catch(e){}if(!u)return false;var r=(u.rol||'').toLowerCase();return r.indexOf('meser')!==-1||r.indexOf('bartender')!==-1||r.indexOf('barman')!==-1;}catch(e){return false;}}
function esBartender(){try{var u=typeof usuario!=='undefined'?usuario:null;if(!u)try{u=JSON.parse(localStorage.getItem('usuario')||'null');}catch(e){}if(!u)return false;var r=(u.rol||'').toLowerCase();return r.indexOf('bartender')!==-1||r.indexOf('barman')!==-1;}catch(e){return false;}}
function tienePermiso(codigo){if(!codigo)return true;if(esAdmin())return true;var perms=[];try{if(typeof PERMISOS_USUARIO!=='undefined'&&Array.isArray(PERMISOS_USUARIO))perms=PERMISOS_USUARIO;else if(typeof usuario!=='undefined'&&usuario&&Array.isArray(usuario.permisos))perms=usuario.permisos;else {var ls=JSON.parse(localStorage.getItem('usuario')||'{}');if(Array.isArray(ls.permisos))perms=ls.permisos;}}catch(e){}return perms.indexOf(codigo)!==-1;}
function mostrarAccesoRestringido(){try{var __ahora=Date.now();if(window.__ultimoAvisoAcceso&&__ahora-window.__ultimoAvisoAcceso<5000)return;window.__ultimoAvisoAcceso=__ahora;}catch(__e){}var msg='<div style="display:flex;align-items:center;gap:10px"><span style="font-size:1.4rem">\uD83D\uDEAB</span><div><div style="font-weight:800">Acceso Restringido</div><div style="font-size:.82rem;opacity:.9">No tienes permisos suficientes para acceder a este m\u00f3dulo.</div></div></div>';try{if(typeof mostrarToast==='function')mostrarToast('danger','\uD83D\uDEAB Acceso Restringido — No tienes permisos suficientes para acceder a este m\u00f3dulo.');}catch(e){}try{var c=null;if(false){var c2=document.getElementById('toastContainer');if(c){var t=document.createElement('div');t.className='toast-cm toast-danger';t.style.cssText='background:linear-gradient(135deg,#dc2626,#991b1b);color:#fff;padding:14px 18px;border-radius:12px;font-weight:700;box-shadow:0 8px 24px rgba(0,0,0,.25)';t.innerHTML=msg;c.appendChild(t);setTimeout(function(){t.style.opacity='0';t.style.transition='opacity .3s';setTimeout(function(){t.remove();},300);},3500);}}catch(e){}void 0}
function filtrarSidebar(){try{var isOp=esRolOperativo();var isAdmin=esAdmin();for(var navId in NAV_PERMISOS){var el=document.getElementById(navId);if(!el)continue;if(navId==='navMesas'&&isAdmin){try{var li0=el.closest('li');if(li0)li0.style.display='none';else el.style.display='none';}catch(_e){}continue;}if(navId==='navFinanzas'){try{var liF=el.closest('li');if(liF)liF.style.display=isAdmin?'':'none';else el.style.display=isAdmin?'':'none';}catch(_e){}continue;}if(navId==='navCaja'&&isAdmin){try{var liC=el.closest('li');if(liC)liC.style.display='none';else el.style.display='none';}catch(_e){}continue;}var req=NAV_PERMISOS[navId];var visible=tienePermiso(req);if(navId==='navAnalisisInventario'&&!visible){var li2=el.closest('li');if(li2)li2.style.display='none';else el.style.display='none';continue;}if(navId==='navUsuarios'&&isOp&&!visible){visible=true;var sp=el.querySelector('span');if(sp)sp.textContent='Fichaje';el.title='Fichaje';}var li=el.closest('li');if(li)li.style.display=visible?'':'none';else el.style.display=visible?'':'none';}if(isAdmin){try{var mA=document.getElementById('navMesas');if(mA){var mlA=mA.closest('li');if(mlA)mlA.style.display='none';else mA.style.display='none';}var fA=document.getElementById('navFinanzas');if(fA){var flA=fA.closest('li');if(flA)flA.style.display='';else fA.style.display='';}var cA=document.getElementById('navCaja');if(cA){var clA=cA.closest('li');if(clA)clA.style.display='none';else cA.style.display='none';}}catch(_e){}}else{try{var fN=document.getElementById('navFinanzas');if(fN){var flN=fN.closest('li');if(flN)flN.style.display='none';else fN.style.display='none';}}catch(_e){}}if(!isAdmin&&esBartender()){try{['navInventario','navAnalisisInventario','navConfiguracion','navConfigInventario','navCaja','navProveedores','navCompras','navReportes','navFacturacion','navMermas','navSpeedBar','navSocios','navVales','navFinanzas'].forEach(function(n){var e=document.getElementById(n);if(e){var l=e.closest('li');if(l)l.style.display='none';else e.style.display='none';}});var mb=document.getElementById('navMesas');if(mb){var mlb=mb.closest('li');if(mlb)mlb.style.display='';}var nb=document.getElementById('navUsuarios');if(nb){var nlb=nb.closest('li');if(nlb)nlb.style.display='';var spb=nb.querySelector('span');if(spb)spb.textContent='Fichaje';}}catch(_e){}}
if(isOp){var mes=document.getElementById('navMesas');if(mes){var ml=mes.closest('li');if(ml)ml.style.display='';} var nu=document.getElementById('navUsuarios');if(nu){var nl=nu.closest('li');if(nl)nl.style.display='';}} if(!tienePermiso('can_access_inventory_analytics')){var an=document.getElementById('navAnalisisInventario');if(an){var al=an.closest('li');if(al)al.style.display='none';else an.style.display='none';}} }catch(e){console.error('filtrarSidebar',e);}}
function puedeCrearPedidos(){if(typeof cajaEstaAbierta==='function'&&!cajaEstaAbierta())return false;if(esAdmin())return true;return tienePermiso('can_create_orders');}
function verificarAcceso(codigo){if(codigo==='can_access_inventory_analytics'&&!tienePermiso(codigo)){mostrarAccesoRestringido();return false;}if(tienePermiso(codigo))return true;mostrarAccesoRestringido();return false;}
function aplicarGuardasNavegacion(){for(var fn in MODULO_PERMISOS){(function(n,c){if(typeof window[n]!=='function')return;var orig=window[n];window[n]=function(){if(n==='iniciarUsuarios'&&esRolOperativo()){var r=orig.apply(this,arguments);setTimeout(function(){try{if(!tienePermiso('crear_usuarios')){var b=document.querySelector('[onclick="modalNuevoUsuario()"]');if(b) b.style.display='none'; document.querySelectorAll('#contenedorRoles').forEach(function(e){e.closest('.card').style.display='none';});} }catch(e){}},400);return r;}if(!tienePermiso(c)){mostrarAccesoRestringido();return;}return orig.apply(this,arguments);};})(fn,MODULO_PERMISOS[fn]);}try{window.addEventListener('hashchange',function(){var h=(location.hash||'').toLowerCase();var p=(location.pathname||'').toLowerCase();var mapa={'#reportes':'ver_reportes','#configuracion':'gestionar_configuracion','#caja':'ver_caja','#mermas':'registrar_mermas','#facturas':'ver_caja','#facturacion':'ver_caja','#inventario':'gestionar_inventario','#analisis':'can_access_inventory_analytics','/reportes':'ver_reportes','/configuracion':'gestionar_configuracion','/caja':'ver_caja','/mermas':'registrar_mermas','/facturas':'ver_caja','/analisis':'can_access_inventory_analytics'};for(var k in mapa){if((h.indexOf(k)!==-1||p.indexOf(k)!==-1)&&!tienePermiso(mapa[k])){mostrarAccesoRestringido();location.hash='#mesas';history.replaceState(null,'','/app');break;}}});var pp=(location.pathname||'').toLowerCase();if(pp.indexOf('/app/')!==-1){var seg=pp.split('/app/')[1]||'';var mp={'reportes':'ver_reportes','configuracion':'gestionar_configuracion','caja':'ver_caja','mermas':'registrar_mermas','facturas':'ver_caja','facturacion':'ver_caja','inventario':'gestionar_inventario','analisis':'can_access_inventory_analytics'};for(var s in mp){if(seg.indexOf(s)!==-1&&!tienePermiso(mp[s])){mostrarAccesoRestringido();history.replaceState(null,'','/app');break;}}} }catch(e){}}
if(typeof PERMISOS_USUARIO==='undefined'){ var PERMISOS_USUARIO=[]; } else { PERMISOS_USUARIO = window.PERMISOS_USUARIO || PERMISOS_USUARIO; window.PERMISOS_USUARIO = PERMISOS_USUARIO; }
function cargarPermisosUsuario(cb){try{var u=typeof usuario!=='undefined'?usuario:null;if(!u)try{u=JSON.parse(localStorage.getItem('usuario')||'{}');}catch(e){}var curPerms = (typeof PERMISOS_USUARIO!=='undefined'&&Array.isArray(PERMISOS_USUARIO)&&PERMISOS_USUARIO.length)?PERMISOS_USUARIO:(u&&Array.isArray(u.permisos)?u.permisos:[]);if(curPerms.length){PERMISOS_USUARIO=curPerms.slice();window.PERMISOS_USUARIO=PERMISOS_USUARIO;}if(!u||!u.id_rol){filtrarSidebar();if(typeof cb==='function')cb();return;}fetch((typeof API_BASE!=='undefined'?API_BASE:'')+'/api/roles/'+u.id_rol+'/permisos',{credentials:'include'}).then(function(r){return r.json();}).then(function(d){if(d.success&&d.permisos){PERMISOS_USUARIO=d.permisos.map(function(p){return p.codigo;});window.PERMISOS_USUARIO=PERMISOS_USUARIO;try{if(u) {u.permisos=PERMISOS_USUARIO.slice();localStorage.setItem('usuario',JSON.stringify(u));if(typeof usuario!=='undefined')usuario.permisos=PERMISOS_USUARIO.slice();}}catch(e){}}filtrarSidebar();if(typeof cb==='function')cb();}).catch(function(){filtrarSidebar();if(typeof cb==='function')cb();});}catch(e){filtrarSidebar();if(typeof cb==='function')cb();}}
document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){try{cargarPermisosUsuario(function(){filtrarSidebar();aplicarGuardasNavegacion();});}catch(e){}},600);});
